require './lib/vehicle'
require './lib/passenger'
require './lib/park'

RSpec.describe Park do
  describe "Iteration 3" do
    it "exists" do
      congress_park = Park.new("Congress Park", 10)

      expect(congress_park).to be_instance_of(Park)
    end

    it "has a name and admission price" do
      congress_park = Park.new("Congress Park", 10)

      expect(congress_park.name).to eq("Congress Park")
      expect(congress_park.price).to eq(10)
    end

    it "has vehicles that entered the park, as well as a way to read that data" do
      congress_park = Park.new("Congress Park", 10)
      vehicle1 = Vehicle.new("2001", "Honda", "Civic")
      vehicle2 = Vehicle.new("2010", "Ford", "Taurus")
      vehicle3 = Vehicle.new("2020", "Toyota", "Rav4")

      expect(congress_park.vehicles).to eq([])

      congress_park.add_vehicle(vehicle1)
      congress_park.add_vehicle(vehicle2)
      congress_park.add_vehicle(vehicle3)

      expect(congress_park.vehicles).to eq([vehicle1, vehicle2, vehicle3])
    end
  end
end


# Each park has vehicles that entered the park, as well as a way to read that data.
# Each park can list all passengers that were in the vehicles that entered the park.
# Each park can calculate revenue generated. Revenue is generated by charging the admission price per adult that entered the park.
# Build upon your existing code from the first two iterations to implement this functionality.